language: ruby
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
before_install: gem install bundler -v 1.10.6
env:
  global:
    - ENDPOINT=https://api.clicksign-demo.com
    - secure: "CFtjot3aotVn5iVOxfrFQZFsNQZyn+0M9BiBzwfuG0egTsyJN2AGV9yrSz7C9/EJpW6qEjYYJiK0C7oxvvfMkuzDVjOUDn1uMQmjIqtthkSwPuuQ5F4poZNYhiBezZSuCP5aupclum7Axh+8Dk/0xJIkz4gqWnqRD2RWYk444dc="
notifications:
  email:
    on_sucess: never
    on_failure: never
